config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root 'home#index'
  resources :users, only: [:index, :show]
  resources :schedules
  resources :schedule_wizard, only: [] do
    resources :steps, only: [:show, :update], controller: :schedule_wizard
  end

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  has_many :user_schedules
  has_many :users, through: :user_schedules
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_schedules
  has_many :schedules, through: :user_schedules

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :timeoutable, authentication_keys: [:login_name]

  validates :username, presence: true
  validates :login_name, presence: true, uniqueness: true

  private
  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/models/user_schedule.rb
class UserSchedule < ActiveRecord::Base
  belongs_to :user
  belongs_to :schedule
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/schedule_wizard_controller.rb
class ScheduleWizardController < ApplicationController
  include Wicked::Wizard
  steps :edit, :confirm
  before_action :authenticate_user!

  def show
    @schedule = Schedule.find(params[:schedule_wizard_id])
    session[:schedule_wizard] = {params[:schedule_wizard_id] => @schedule}
    render_wizard
  end

  def update
    case step
    when :edit
      @schedule = session[:schedule_wizard][params[:schedule_wizard_id]]
      @schedule.assign_attributes(schedule_params)
      render_step next_step

    when :confirm
      @schedule = session[:schedule_wizard][params[:schedule_wizard_id]]
      @schedule.save!
      flash[:notice] = "更新が完了しました。"
      redirect_to schedules_path
    end
  end

  private
  def schedule_params
    params.require(:schedule).permit(:scheduled_on, :description, :lock_version, {user_ids: []})
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :update, :destroy]
  before_action :authenticate_user!

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
    redirect_to schedule_wizard_step_path(:edit, schedule_wizard_id: params[:id])
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      begin
        @schedule.update!(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      rescue ActiveRecord::StaleObjectError
        flash.now[:alert] = '別の処理で更新されています。'
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:scheduled_on, :description, :lock_version, :user_ids)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, only: [:create, :update]

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:account_update) << :username
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  before_action :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hbr(text)
    h(text).gsub(/\r\n?|\n/, "<br />").html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/schedule_wizard_helper.rb
module ScheduleWizardHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsStudy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
  <%= link_to "Account edit", edit_user_registration_path %><br />
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/schedule_wizard/confirm.html.erb
<h1>Confirm schedule</h1>

<%= form_for(@schedule, url: schedule_wizard_step_path(id: :confirm), method: :put) do |f| %>
  <dl class="dl-horizontal">
    <dt><%= f.label :scheduled_on %></dt>
    <dd><%= f.object.scheduled_on %></dd>
    <dt><%= f.label :description %></dt>
    <dd><%= hbr f.object.description %></dd>
    <dt><%= f.label :users %></dt>
    <dd>
      <% f.object.users.each do |user| %>
        <%= user.username %><br />
      <% end %>
    </dd>
  </dl>
  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

<%= link_to 'Back', previous_wizard_path %>

app/views/schedule_wizard/edit.html.erb
<h1>Editing schedule</h1>

<%= form_for(@schedule, url: schedule_wizard_step_path(id: :edit), method: :put) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <dl class="dl-horizontal">
    <dt><%= f.label :scheduled_on %></dt>
    <dd><%= f.date_field :scheduled_on, class: "form-control" %></dd>
  </dl>
  <dl class="dl-horizontal">
    <dt><%= f.label :description %></dt>
    <dd><%= f.text_area :description, class: "form-control" %></dd>
  </dl>
  <dl class="dl-horizontal">
    <dt><%= f.label :user %></dt>
    <dd>
      <%= collection_check_boxes :schedule, :user_ids, User.all, :id, :username do |b| %>
        <%= b.label(class: "checkbox-inline") { b.check_box + b.text } %>
      <% end %>
    </dd>
  </dl>
  <%= f.hidden_field :lock_version %>
  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :scheduled_on %><br>
    <%= f.date_field :scheduled_on %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%= collection_select :schedule, :user_ids, User.all, :id, :username, include_blank: true %>
  </div>
  <%= f.hidden_field :lock_version %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<h1>Listing schedules</h1>

<table>
  <thead>
    <tr>
      <th>Scheduled on</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.scheduled_on %></td>
        <td><%= hbr schedule.description %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Scheduled on:</strong>
  <%= @schedule.scheduled_on %>
</p>

<p>
  <strong>Description:</strong>
  <%= @schedule.description %>
</p>

<p>
  <strong>Users:</strong>
  <% @schedule.users.each do |user| %>
    <%= user.username %>
  <% end %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Encrypted password:</strong>
  <%= @user.encrypted_password %>
</p>

<p>
  <strong>Reset password token:</strong>
  <%= @user.reset_password_token %>
</p>

<p>
  <strong>Reset password sent at:</strong>
  <%= @user.reset_password_sent_at %>
</p>

<p>
  <strong>Remember created at:</strong>
  <%= @user.remember_created_at %>
</p>

<p>
  <strong>Sign in count:</strong>
  <%= @user.sign_in_count %>
</p>

<p>
  <strong>Current sign in at:</strong>
  <%= @user.current_sign_in_at %>
</p>

<p>
  <strong>Last sign in at:</strong>
  <%= @user.last_sign_in_at %>
</p>

<p>
  <strong>Current sign in ip:</strong>
  <%= @user.current_sign_in_ip %>
</p>

<p>
  <strong>Last sign in ip:</strong>
  <%= @user.last_sign_in_ip %>
</p>

<p>
  <strong>Confirmation token:</strong>
  <%= @user.confirmation_token %>
</p>

<p>
  <strong>Confirmed at:</strong>
  <%= @user.confirmed_at %>
</p>

<p>
  <strong>Confirmation sent at:</strong>
  <%= @user.confirmation_sent_at %>
</p>

<p>
  <strong>Unconfirmed email:</strong>
  <%= @user.unconfirmed_email %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @user.created_at %>
</p>

<p>
  <strong>Updated_at:</strong>
  <%= @user.updated_at %>
</p>

<%= link_to 'Back', users_path %>